ask_for_approval = "never"
sandbox = "workspace-write"
model = "gpt-5.2-Gemini"
model_reasoning_effort = "medium"
personality = "pragmatic"
suppress_unstable_features_warning = true

[features]
experimental_windows_sandbox = true
elevated_windows_sandbox = true
powershell_utf8 = true
collab = true
steer = true
unified_exec = true
apps = true
shell_snapshot = true

[projects.'\\?\C:\Users\codym\Downloads\LexiProApp-MARKET-READY-Phase5-ShadowDOM']
trust_level = "trusted"

[projects.'C:\Users\codym\Downloads\LexiProApp-MARKET-READY-Phase5-ShadowDOM']
trust_level = "trusted"

[projects.'C:\Users\codym\Downloads\Enterprise-main (9)']
trust_level = "trusted"

[projects.'C:\Users\codym']
trust_level = "untrusted"

[projects.'\\?\C:\Users\codym\Downloads\Enterprise-main (9)\Enterprise-main']
trust_level = "trusted"

[projects.'C:\WINDOWS\system32']
trust_level = "trusted"

[projects.'C:\Windows\System32']
trust_level = "trusted"

[notice]
hide_full_access_warning = true


